// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuoteApi.Data;

#nullable disable

namespace QuoteApi.Migrations
{
    [DbContext(typeof(QuoteContext))]
    [Migration("20230108174124_RemoveIdentityProperty")]
    partial class RemoveIdentityProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("QuoteApi.Data.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QuoteCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCreator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCreatorNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TheQuote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WhenWasSaid")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhoSaid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
